import React, { createContext, useState, useEffect } from 'react';

export const LanguageContext = createContext();

const translations = {
  bn: {
    // ── Navigation ──────────────────────────────────────────────
    home: 'হোম',
    slots: 'স্লটস',
    casino: 'ক্যাসিনো',
    profile: 'আমার অ্যাকাউন্ট',

    // ── Auth Buttons ─────────────────────────────────────────────
    login: 'লগইন',
    signup: 'নিবন্ধন',
    logout: 'লগআউট',

    // ── Balance / Wallet ─────────────────────────────────────────
    deposit: 'জমা করুন',
    withdrawal: 'উত্তোলন',
    refreshBalance: 'ব্যালেন্স রিফ্রেশ করুন',

    // ── Sidebar ──────────────────────────────────────────────────
    liveChat: '২৪/৭ লাইভ চ্যাট',
    language: 'ভাষা',
    downloadApp: 'অ্যাপ ডাউনলোড করুন',
    downloadAppNow: 'এখনই অ্যাপ ডাউনলোড করুন',
    loading: 'লোড হচ্ছে...',
    loadingCategories: 'ক্যাটাগরি লোড হচ্ছে...',
    loadingContactOptions: 'যোগাযোগের বিকল্প লোড হচ্ছে...',
    viewAll: 'সব দেখুন',
    promotions: 'প্রচারমূলক অফার',
    bonuses: 'বোনাস',
    // ── Bottom Menu Items ─────────────────────────────────────────
    vipClub: 'ভিআইপি ক্লাব',
    referralProgram: 'রেফারেল প্রোগ্রাম',
    affiliate: 'অ্যাফিলিয়েট',
    brandAmbassadors: 'ব্র্যান্ড অ্যাম্বাসেডর',
    appDownload: 'অ্যাপ ডাউনলোড',
    contactUs: 'যোগাযোগ করুন',
    newMemberGuide: 'নতুন সদস্য গাইড',
    bjForum: 'বিজে ফোরাম',

    // ── Profile Dropdown ──────────────────────────────────────────
    username: 'ব্যবহারকারীর নাম',
    playerId: 'প্লেয়ার আইডি',
    notifications: 'বিজ্ঞপ্তি',
    personalInfo: 'ব্যক্তিগত তথ্য',
    loginSecurity: 'লগইন ও নিরাপত্তা',
    verification: 'যাচাইকরণ',
    transactions: 'লেনদেনের রেকর্ড',
    bettingRecords: 'বেটিং রেকর্ড',
    turnover: 'টার্নওভার',
    myReferral: 'আমার রেফারেল',

    // ── Mobile App Banner ─────────────────────────────────────────
    downloadOurApp: 'আমাদের অ্যাপ ডাউনলোড করুন',
    betterExperience: 'উন্নত অভিজ্ঞতা ও এক্সক্লুসিভ বোনাস',
    download: 'ডাউনলোড',

    // ── Mobile Bottom Bar ─────────────────────────────────────────
    menu: 'মেনু',
    app: 'অ্যাপ',

    // ── Signup Success Popup ──────────────────────────────────────
    signupSuccess: 'সফলভাবে নিবন্ধিত হয়েছেন',
    signupSuccessMessage:
      'আপনার নিবন্ধন সম্পন্ন হয়েছে এবং খেলার উত্তেজনার জন্য প্রস্তুত হন! স্পোর্টস বেটিং এর দুনিয়া এখন আপনার হাতের মুঠোয়। আপনার বেটে শুভকামনা!',
    depositNow: 'এখনই জমা করুন',

    // ── Contact Platforms ─────────────────────────────────────────
    whatsapp: 'হোয়াটসঅ্যাপ',
    email: 'ইমেইল',
    facebook: 'ফেসবুক',
    instagram: 'ইনস্টাগ্রাম',
    telegram: 'টেলিগ্রাম',
    twitter: 'টুইটার',

    // ── APK Toast ────────────────────────────────────────────────
    apkDownloadStarted: 'এপিকে ডাউনলোড শুরু হয়েছে!',
    failedRefreshBalance: 'ব্যালেন্স রিফ্রেশ ব্যর্থ হয়েছে',

    // ── Register / Login Page ─────────────────────────────────────
    tabLogin: 'লগইন',
    tabSignup: 'নিবন্ধন',
    phoneNumber: 'ফোন নম্বর',
    enterPhoneNumber: 'ফোন নম্বর লিখুন',
    usernameLabel: 'ব্যবহারকারীর নাম',
    enterUsername: 'আপনার নাম লিখুন',
    passwordLabel: 'পাসওয়ার্ড',
    createPassword: 'একটি পাসওয়ার্ড তৈরি করুন',
    confirmPasswordLabel: 'পাসওয়ার্ড নিশ্চিত করুন',
    confirmPasswordPlaceholder: 'আপনার পাসওয়ার্ড নিশ্চিত করুন',
    referralCodeLabel: 'রেফারেল কোড (ঐচ্ছিক)',
    enterReferralCode: 'রেফারেল কোড লিখুন',
    verifyBtn: 'যাচাই করুন',
    checkingBtn: 'যাচাই হচ্ছে...',
    changeBtn: 'পরিবর্তন করুন',
    validReferralCode: '✅ বৈধ রেফারেল কোড',
    referralFrom: 'রেফারেল কোড থেকে',
    otpSentTo: 'এ পাঠানো ৬-সংখ্যার ওটিপি লিখুন',
    otpExpiresIn: 'মেয়াদ শেষ হবে:',
    otpExpired: 'ওটিপির মেয়াদ শেষ',
    backBtn: 'ফিরে যান',
    resendOtp: 'ওটিপি পুনরায় পাঠান',
    resendIn: 'পুনরায় পাঠান',
    pleaseEnterAllDigits: 'অনুগ্রহ করে সব ৬টি সংখ্যা লিখুন',
    sendOtpBtn: 'ওটিপি পাঠান',
    sendingOtpBtn: 'ওটিপি পাঠানো হচ্ছে...',
    verifyOtpBtn: 'ওটিপি যাচাই ও অ্যাকাউন্ট তৈরি করুন',
    verifyingOtpBtn: 'ওটিপি যাচাই হচ্ছে...',
    enterYourUsername: 'আপনার ব্যবহারকারীর নাম লিখুন',
    enterYourPassword: 'আপনার পাসওয়ার্ড লিখুন',
    loginBtn: 'লগইন',
    loggingInBtn: 'লগইন হচ্ছে...',
    forgotPassword: 'পাসওয়ার্ড ভুলে গেছেন?',
    noAccount: 'কোনো অ্যাকাউন্ট নেই?',
    signUpHere: 'এখানে নিবন্ধন করুন',
    toastOtpSent: 'আপনার ফোনে ওটিপি পাঠানো হয়েছে!',
    toastOtpResent: 'ওটিপি সফলভাবে পুনরায় পাঠানো হয়েছে!',
    toastAccountCreated: 'অ্যাকাউন্ট সফলভাবে তৈরি হয়েছে!',
    toastLoginSuccess: 'লগইন সফল হয়েছে!',
    toastReferralValid: 'রেফারেল কোড বৈধ!',
    toastAffiliateWelcome: 'স্বাগতম! আপনাকে একজন অ্যাফিলিয়েট রেফার করেছেন।',
    toastUserReferralWelcome: 'স্বাগতম! আপনার রেফারেল রেকর্ড করা হয়েছে।',
    toastFailedSendOtp: 'ওটিপি পাঠাতে ব্যর্থ। আবার চেষ্টা করুন।',

    // ── Category Names ────────────────────────────────────────────
    exclusive: 'এক্সক্লুসিভ',
    sports: 'স্পোর্টস',
    crash: 'ক্র্যাশ',
    table: 'টেবিল',
    fishing: 'ফিশিং',
    arcade: 'আর্কেড',
    lottery: 'লটারি',

    // ── Notification Page ─────────────────────────────────────────
    pleaseLoginToViewNotifications: 'বিজ্ঞপ্তি দেখতে লগইন করুন',
    failedToFetchNotifications: 'বিজ্ঞপ্তি লোড করতে ব্যর্থ হয়েছে',
    authenticationRequired: 'প্রমাণীকরণ প্রয়োজন',
    signIn: 'সাইন ইন',
    noNotificationsYet: 'এখনো কোন বিজ্ঞপ্তি নেই',
    weWillNotifyYou: 'গুরুত্বপূর্ণ কিছু হলে আমরা আপনাকে জানিয়ে দেব।',
    showing: 'দেখানো হচ্ছে',
    of: 'এর',
    previous: 'পূর্ববর্তী',
    next: 'পরবর্তী',
    todayAt: 'আজ',
    yesterdayAt: 'গতকাল',
    invalidDate: 'অবৈধ তারিখ',
    notificationsPageTitle: 'বিজ্ঞপ্তি',

    // ── Profile Page ──────────────────────────────────────────────
    passwordsDontMatch: 'নতুন পাসওয়ার্ড মেলেনি!',
    passwordMinLength: 'নতুন পাসওয়ার্ড কমপক্ষে ৬ অক্ষরের হতে হবে!',
    passwordChangedSuccess: 'পাসওয়ার্ড সফলভাবে পরিবর্তন করা হয়েছে!',
    failedToChangePassword: 'পাসওয়ার্ড পরিবর্তন করতে ব্যর্থ হয়েছে',
    personalInfoUpdated: 'ব্যক্তিগত তথ্য সফলভাবে আপডেট করা হয়েছে!',
    failedToUpdateInfo: 'তথ্য আপডেট করতে ব্যর্থ হয়েছে',
    verificationEmailSent: 'যাচাইকরণ ইমেল পাঠানো হয়েছে। অনুগ্রহ করে আপনার ইনবক্স চেক করুন।',
    verificationSmsSent: 'যাচাইকরণ এসএমএস পাঠানো হয়েছে। অনুগ্রহ করে আপনার ফোন চেক করুন।',
    verifiedSuccessfully: 'সফলভাবে যাচাই করা হয়েছে!',
    failedToVerify: 'যাচাই করতে ব্যর্থ হয়েছে',
    failedToUpdate2FA: '2FA সেটিংস আপডেট করতে ব্যর্থ হয়েছে',
    verified: 'যাচাইকৃত',
    pending: 'মুলতুবি',
    notStarted: 'শুরু হয়নি',
    rejected: 'প্রত্যাখ্যাত',
    copiedToClipboard: 'কপি করা হয়েছে!',
    edit: 'সম্পাদনা',
    saving: 'সংরক্ষণ করা হচ্ছে...',
    save: 'সংরক্ষণ',
    cancel: 'বাতিল',
    notSet: 'সেট করা হয়নি',
    fullLegalName: 'পূর্ণ আইনি নাম',
    enterFullName: 'আপনার পূর্ণ নাম লিখুন',
    dateOfBirth: 'জন্ম তারিখ',
    phone: 'ফোন',
    enterPhoneNumber: 'আপনার ফোন নম্বর লিখুন',
    email: 'ইমেইল',
    manage: 'পরিচালনা',
    changePassword: 'পাসওয়ার্ড পরিবর্তন করুন',
    currentPassword: 'বর্তমান পাসওয়ার্ড',
    newPassword: 'নতুন পাসওয়ার্ড',
    confirmNewPassword: 'নতুন পাসওয়ার্ড নিশ্চিত করুন',
    securitySettings: 'নিরাপত্তা সেটিংস',
    twoFactorAuth: 'টু-ফ্যাক্টর অথেন্টিকেশন',
    extraSecurityLayer: 'নিরাপত্তার একটি অতিরিক্ত স্তর যোগ করুন',
    enable: 'সক্রিয় করুন',
    disable: 'নিষ্ক্রিয় করুন',
    loginAlerts: 'লগইন সতর্কতা',
    notifyNewLogins: 'নতুন লগইন সম্পর্কে বিজ্ঞপ্তি পান',
    enabled: 'সক্রিয়',
    activeSessions: 'সক্রিয় সেশন',
    manageActiveLogins: 'আপনার সক্রিয় লগইনগুলি পরিচালনা করুন',
    viewAll: 'সব দেখুন',
    verificationDescription: 'সমস্ত বৈশিষ্ট্য অ্যাক্সেস করতে এবং আপনার সীমা বাড়াতে আপনার যাচাইকরণ সম্পূর্ণ করুন।',
    emailVerification: 'ইমেইল যাচাইকরণ',
    emailVerificationDesc: 'গুরুত্বপূর্ণ বিজ্ঞপ্তি এবং আপডেট পেতে আপনার ইমেল ঠিকানা যাচাই করুন।',
    verifyEmail: 'ইমেইল যাচাই করুন',
    phoneVerification: 'ফোন যাচাইকরণ',
    phoneVerificationDesc: 'অতিরিক্ত নিরাপত্তা এবং দ্রুত উত্তোলনের জন্য আপনার ফোন নম্বর যাচাই করুন।',
    verifyPhone: 'ফোন যাচাই করুন',
    identityVerification: 'পরিচয় যাচাইকরণ',
    identityVerificationDesc: 'আপনার পরিচয় যাচাই করতে একটি সরকারি আইডি আপলোড করুন।',
    startVerification: 'যাচাই শুরু করুন',
    addressVerification: 'ঠিকানা যাচাইকরণ',
    addressVerificationDesc: 'সাম্প্রতিক ইউটিলিটি বিল বা ব্যাংক স্টেটমেন্ট দিয়ে আপনার ঠিকানা যাচাই করুন।',
    verifyAddress: 'ঠিকানা যাচাই করুন',
    resendCode: 'কোড পুনরায় পাঠান',
    enterVerificationCode: 'যাচাইকরণ কোড লিখুন:',

    // ── Transaction Page ──────────────────────────────────────────
    transactionRecords: 'লেনদেনের রেকর্ড',
    filters: 'ফিল্টার',
    type: 'ধরন',
    status: 'স্ট্যাটাস',
    startDate: 'শুরুর তারিখ',
    endDate: 'শেষ তারিখ',
    allTypes: 'সব ধরন',
    allStatus: 'সব স্ট্যাটাস',
    clearFilters: 'ফিল্টার মুছুন',
    applyFilters: 'ফিল্টার প্রয়োগ করুন',
    failedToFetchTransactions: 'লেনদেন আনতে ব্যর্থ হয়েছে',
    failedToLoadTransactions: 'লেনদেন লোড করতে ব্যর্থ হয়েছে। আবার চেষ্টা করুন।',
    noTransactionsFound: 'কোন লেনদেন পাওয়া যায়নি',
    tryAgain: 'আবার চেষ্টা করুন',
    completed: 'সম্পূর্ণ',
    failed: 'ব্যর্থ',
    cancelled: 'বাতিল',
    bank: 'ব্যাংক',
    crypto: 'ক্রিপ্টো',
    currencySymbol: '৳',
    dateFormat: 'MMM dd, yyyy HH:mm',

    // ── Betting Records Page ──────────────────────────────────────
    bettingRecords: 'বেটিং রেকর্ড',
    settled: 'নিষ্পত্তিকৃত',
    unsettled: 'অনিষ্পত্তিকৃত',
    last7Days: 'গত ৭ দিন',
    transaction: 'লেনদেন',
    game: 'গেম',
    betAmount: 'বাজির পরিমাণ',
    winAmount: 'জয়ের পরিমাণ',
    netAmount: 'নেট পরিমাণ',
    dateTime: 'তারিখ ও সময়',
    platform: 'প্ল্যাটফর্ম',
    gameType: 'গেমের ধরন',
    won: 'জিতেছেন',
    lost: 'হারিয়েছেন',
    failedToFetchBettingRecords: 'বেটিং রেকর্ড আনতে ব্যর্থ হয়েছে',
    loadingBettingRecords: 'বেটিং রেকর্ড লোড হচ্ছে...',
    retry: 'পুনরায় চেষ্টা করুন',
    noSettledRecords: 'কোন নিষ্পত্তিকৃত বেটিং রেকর্ড পাওয়া যায়নি',
    noUnsettledRecords: 'কোন অনিষ্পত্তিকৃত বেটিং রেকর্ড পাওয়া যায়নি',
    cricket: 'ক্রিকেট',
    football: 'ফুটবল',
    tennis: 'টেনিস',
    basketball: 'বাস্কেটবল',
    refreshCoinBalance: "কয়েন ব্যালেন্স রিফ্রেশ করুন",
    coinBalanceRefreshed: "কয়েন ব্যালেন্স রিফ্রেশ হয়েছে!",
    failedRefreshCoinBalance: "কয়েন ব্যালেন্স রিফ্রেশ করতে ব্যর্থ হয়েছে",
    // Add to bn object (after existing entries)
    exclusiveBonuses: 'এক্সক্লুসিভ বোনাস ও পুরস্কার',
    claimCashBonusesDesc: 'তাত্ক্ষণিক ক্যাশ বোনাস, বিশেষ অফার এবং রয়্যালটি রিওয়ার্ড সরাসরি আপনার ওয়ালেট ব্যালেন্সে দাবি করুন',
    availableBonuses: 'উপলব্ধ বোনাস',
    claimCashBonuses: 'ক্যাশ বোনাস দাবি করুন যা সরাসরি আপনার অ্যাকাউন্ট ব্যালেন্সে যুক্ত হবে',
    failedToFetchBonuses: 'বোনাস আনতে ব্যর্থ হয়েছে',
    pleaseLoginToViewBonuses: 'বোনাস দেখতে অনুগ্রহ করে লগইন করুন',
    checkBackLater: 'বিশেষ অফার এবং বোনাসের জন্য পরে আবার চেক করুন।',
    bonusDetails: 'বোনাসের বিবরণ',
    validity: 'বৈধতা',
    created: 'তৈরি করা হয়েছে',
    expires: 'মেয়াদ শেষ হবে',
    never: 'কখনই না',
    neverExpires: ' মেয়াদ শেষ হবে না',
    expired: 'মেয়াদ উত্তীর্ণ',
    expiresToday: 'আজ মেয়াদ শেষ হবে',
    daysLeft: 'দিন বাকি',
    claimNow: 'এখনই দাবি করুন',
    claimBonus: 'বোনাস দাবি করুন',
    confirmClaimMessage: 'আপনি কি নিশ্চিত আপনি এই বোনাস দাবি করতে চান?',
    confirmClaim: 'দাবি নিশ্চিত করুন',
    bonus: 'বোনাস',
    amount: 'পরিমাণ',
    type: 'ধরন',
    occasion: 'অবসর',
    invalidDate: 'অবৈধ তারিখ',
    noExpiry: 'কোন মেয়াদ শেষ নেই',
    todayAt: 'আজ',
    // ── Turnover Page ─────────────────────────────────────────────
    turnoverRequirement: 'টার্নওভার প্রয়োজনীয়তা',
    turnoverDescription: 'উত্তোলন সক্ষম করতে ওয়েজারিং প্রয়োজনীয়তা সম্পূর্ণ করুন',
    refresh: 'রিফ্রেশ',
    loadingTurnoverData: 'টার্নওভার ডাটা লোড হচ্ছে...',
    failedToFetchUserData: 'ব্যবহারকারীর ডাটা আনতে ব্যর্থ হয়েছে',
    pleaseLoginToViewProfile: 'আপনার প্রোফাইল দেখতে লগইন করুন',
    noTurnoverRequirement: 'কোন টার্নওভার প্রয়োজনীয়তা নেই',
    noTurnoverRequirementDesc: 'আপনার বর্তমানে কোন ওয়েজারিং প্রয়োজনীয়তা নেই।',
    freeWithdrawalMessage: 'কোন টার্নওভার সীমাবদ্ধতা না থাকায় আপনি স্বাধীনভাবে উত্তোলন করতে পারেন।',
    wageringRequirement: 'ওয়েজারিং প্রয়োজনীয়তা',
    betDepositMultiplier: 'আপনার ডিপোজিটের {multiplier} গুণ বাজি রাখুন',
    inProgress: 'চলমান',
    progress: 'অগ্রগতি',
    depositAmount: 'ডিপোজিট পরিমাণ',
    requiredTurnover: 'প্রয়োজনীয় টার্নওভার',
    completedWagering: 'সম্পন্ন ওয়েজারিং',
    remaining: 'বাকি',
    wageringCompleted: 'ওয়েজারিং প্রয়োজনীয়তা সম্পন্ন!',
    wageringCompletedDesc: 'আপনি সফলভাবে ওয়েজারিং প্রয়োজনীয়তা সম্পন্ন করেছেন। আপনি এখন উত্তোলন করতে পারেন।',
    wageringPending: 'ওয়েজারিং প্রয়োজনীয়তা pending',
    wageringPendingDesc: 'প্রয়োজনীয়তা সম্পন্ন করতে আপনাকে আরও {currency}{amount} বাজি রাখতে হবে।',
    currentProgress: 'বর্তমান অগ্রগতি',
    howTurnoverWorks: 'টার্নওভার কিভাবে কাজ করে',
    depositTurnover: 'ডিপোজিট টার্নওভার',
    depositTurnoverDesc: 'উত্তোলন করার আগে আপনাকে আপনার ডিপোজিট পরিমাণের {multiplier} গুণ ({currency}{amount}) বাজি রাখতে হবে।',
    wageringProgress: 'ওয়েজারিং অগ্রগতি',
    wageringProgressDesc: 'আপনার বর্তমান বাজির পরিমাণ {currency}{completed} প্রয়োজনীয় {currency}{required} এর মধ্যে।',
    importantNotes: 'গুরুত্বপূর্ণ নোট',
    importantNote1: 'উত্তোলন করার আগে আপনাকে ওয়েজারিং প্রয়োজনীয়তা সম্পন্ন করতে হবে',
    importantNote2: 'শুধুমাত্র নিষ্পত্তিকৃত বাজি ওয়েজারিং প্রয়োজনীয়তার জন্য গণনা করা হয়',
    importantNote3: 'প্রয়োজনীয় টার্নওভার: {multiplier} × {currency}{deposit} = {currency}{required}',
    importantNote4: 'ওয়েজারিং সম্পন্ন না হওয়া পর্যন্ত উত্তোলন সীমাবদ্ধ',
    currentBalance: 'বর্তমান ব্যালেন্স',
    totalDeposit: 'মোট ডিপোজিট',
    totalBet: 'মোট বাজি',
    turnoverStatus: 'টার্নওভার স্ট্যাটাস',
    complete: 'সম্পন্ন',
bonuses: 'বোনাস',
noBonusesAvailable: 'কোন বোনাস উপলব্ধ নেই',
noBonusesMessage: 'আপাতত আপনার কোনো বোনাস উপলব্ধ নেই। পরবর্তীতে নতুন অফার এবং পুরস্কারের জন্য আবার দেখুন!',
// ── Bottom Menu Items ─────────────────────────────────────────
vipClub: 'ভিআইপি ক্লাব',
    // ── My Referral Page ──────────────────────────────────────────
    info: 'তথ্য',
    details: 'বিস্তারিত',
    yourReferralCode: 'আপনার রেফারেল কোড',
    copyReferralCode: 'রেফারেল কোড কপি করুন',
    shareCodeMessage: 'পুরস্কার অর্জন করতে বন্ধুদের সাথে এই কোড শেয়ার করুন',
    copyLink: 'লিংক কপি করুন',
    share: 'শেয়ার করুন',
    activeDownlines: 'সক্রিয় ডাউনলাইন',
    lifetimeRewards: 'লাইফটাইম রিওয়ার্ড',
    referralTurnover: 'রেফারেল টার্নওভার',
    cashRewards: 'ক্যাশ রিওয়ার্ড',
    referredUsers: 'রেফার্ড ইউজার',
    userId: 'ইউজার আইডি',
    joinedDate: 'যোগদানের তারিখ',
    earnedAmount: 'অর্জিত পরিমাণ',
    noReferralsYet: 'এখনো কোন রেফারেল নেই',
    shareReferralMessage: 'রিওয়ার্ড অর্জন শুরু করতে আপনার রেফারেল কোড শেয়ার করুন',
    howReferralWorks: 'আমাদের রেফারেল প্রোগ্রাম কিভাবে কাজ করে',
    shareYourCode: 'আপনার কোড শেয়ার করুন',
    shareCodeDesc: 'আপনার অনন্য রেফারেল কোড বন্ধুদের সাথে শেয়ার করুন। তারা অ্যাপে সাইন আপ করার সময় এটি ব্যবহার করবে।',
    earnRewards: 'রিওয়ার্ড অর্জন করুন',
    earnRewardsDesc: 'যখন আপনার বন্ধু তাদের প্রথম ডিপোজিট করে বা যোগ্য কার্যক্রম সম্পন্ন করে, আপনি রিওয়ার্ড অর্জন করবেন।',
    trackEarnings: 'আপনার আয় ট্র্যাক করুন',
    trackEarningsDesc: 'এই ড্যাশবোর্ডে রিয়েল-টাইমে আপনার রেফারেল আয় এবং পরিসংখ্যান মনিটর করুন।',
    termsConditions: 'শর্তাবলী',
    term1: 'রেফারেল রিওয়ার্ড শর্তাবলী সাপেক্ষে',
    term2: 'রেফারেল সিস্টেমের অপব্যবহার অ্যাকাউন্ট স্থগিতের কারণ হতে পারে',
    term3: 'রিওয়ার্ড আপনার অ্যাকাউন্টে আসতে ২৪ ঘন্টা পর্যন্ত সময় লাগতে পারে',
    term4: 'রেফারেল আয়ের জন্য ন্যূনতম উত্তোলন সীমা প্রযোজ্য হতে পারে',
    joinMe: 'আমার সাথে যোগ দিন!',
    useMyReferralCode: 'সাইন আপ করতে আমার রেফারেল কোড ব্যবহার করুন',
    error: 'ত্রুটি',
    copied: 'কপি করা হয়েছে!',
    internalServerError: 'অভ্যন্তরীণ সার্ভার ত্রুটি',
    // Add these to the bn object (Bengali)
    depositFunds: 'টাকা জমা করুন',
    depositDescription: 'OraclePay নিরাপদ পেমেন্ট গেটওয়ে ব্যবহার করে আপনার অ্যাকাউন্টে টাকা যোগ করুন',
    failedToFetchDepositMethods: 'ডিপোজিট পদ্ধতি লোড করতে ব্যর্থ হয়েছে',
    failedToFetchUserData: 'ব্যবহারকারীর তথ্য আনতে ব্যর্থ হয়েছে',
    loadingDepositMethods: 'ডিপোজিট পদ্ধতি লোড হচ্ছে...',
    noDepositMethodsAvailable: 'বর্তমানে কোন ডিপোজিট পদ্ধতি উপলব্ধ নেই।',
    amountCurrency: 'পরিমাণ (৳)',
    enterDepositAmount: 'জমার পরিমাণ লিখুন',
    selectBonusOptional: 'বোনাস নির্বাচন করুন (ঐচ্ছিক)',
    loadingBonuses: 'বোনাস লোড হচ্ছে...',
    noBonus: 'কোন বোনাস নেই',
    proceedWithoutBonus: 'বোনাস ছাড়া এগিয়ে যান',
    bonusCode: 'কোড',
    noBonusesAvailable: 'বর্তমানে কোন বোনাস উপলব্ধ নেই।',
    transactionSummary: 'লেনদেনের সারাংশ',
    depositAmount: 'জমার পরিমাণ',
    bonus: 'বোনাস',
    totalCredit: 'মোট ক্রেডিট',
    proceedTo: 'এগিয়ে যান',
    payment: 'পেমেন্ট',
    processing: 'প্রসেসিং হচ্ছে...',
    selectPaymentMethod: 'অনুগ্রহ করে একটি পেমেন্ট পদ্ধতি নির্বাচন করুন',
    amountRequired: 'পরিমাণ প্রয়োজন',
    minDepositAmount: 'ন্যূনতম জমার পরিমাণ ৳৫',
    amountMustBeWholeNumber: 'পরিমাণ একটি পূর্ণ সংখ্যা হতে হবে',
    maxDepositAmount: 'সর্বোচ্চ জমার পরিমাণ হল',
    pleaseSelectPaymentMethod: 'অনুগ্রহ করে একটি পেমেন্ট পদ্ধতি নির্বাচন করুন',
    redirectingToPaymentPage: 'পেমেন্ট পৃষ্ঠায় পুনঃনির্দেশিত হচ্ছে...',
    failedToGeneratePayment: 'পেমেন্ট তৈরি করতে ব্যর্থ হয়েছে',
    paymentGenerationFailed: 'পেমেন্ট তৈরি ব্যর্থ হয়েছে। আবার চেষ্টা করুন।',
    invalidPaymentRequest: 'অবৈধ পেমেন্ট অনুরোধ। আপনার ইনপুট চেক করুন।',
    invalidApiToken: 'অবৈধ API টোকেন। সাপোর্টে যোগাযোগ করুন।',
    accessDenied: 'অ্যাক্সেস অস্বীকৃত। সাপোর্টে যোগাযোগ করুন।',
    authenticationTokenNotFound: 'অথেন্টিকেশন টোকেন পাওয়া যায়নি',
    balanceUpdatedSuccessfully: 'ব্যালেন্স সফলভাবে আপডেট হয়েছে!',
    failedToRefreshBalance: 'ব্যালেন্স রিফ্রেশ করতে ব্যর্থ হয়েছে',
    justNow: 'এখনই',
    minutesAgo: 'মিনিট আগে',
    hoursAgo: 'ঘন্টা আগে',
    daysAgo: 'দিন আগে',
    error: 'ত্রুটি',
    tryAgain: 'আবার চেষ্টা করুন',
    currentBalance: 'বর্তমান ব্যালেন্স',
    bonusBalance: 'বোনাস ব্যালেন্স',
    refreshBalance: 'ব্যালেন্স রিফ্রেশ করুন',
    accountInformation: 'অ্যাকাউন্টের তথ্য',
    playerId: 'প্লেয়ার আইডি',
    username: 'ব্যবহারকারীর নাম',
    phone: 'ফোন',
    howToDepositWithOraclePay: 'কিভাবে OraclePay দিয়ে জমা করবেন',
    selectPaymentMethod: 'আপনার পছন্দের পেমেন্ট পদ্ধতি নির্বাচন করুন',
    enterDepositAmountInstruction: 'আপনি যে পরিমাণ জমা করতে চান তা লিখুন',
    selectBonusIfAvailable: 'যদি উপলব্ধ থাকে তবে একটি বোনাস অপশন নির্বাচন করুন (ঐচ্ছিক)',
    clickProceedToPayment: '"প্রসিড টু [পেমেন্ট মেথড] পেমেন্ট" এ ক্লিক করুন',
    redirectedToOraclePay: 'আপনি OraclePay সিকিউর পেমেন্ট পৃষ্ঠায় পুনঃনির্দেশিত হবেন',
    completePayment: 'আপনার নির্বাচিত পদ্ধতি ব্যবহার করে পেমেন্ট সম্পূর্ণ করুন',
    redirectedBack: 'সফল পেমেন্টের পরে, আপনি ফিরে পুনঃনির্দেশিত হবেন',
    balanceUpdated: 'আপনার ব্যালেন্স স্বয়ংক্রিয়ভাবে আপডেট হবে',
    recentTransactions: 'সাম্প্রতিক লেনদেন',
    viewAll: 'সব দেখুন',
    transactionId: 'আইডি',
    session: 'সেশন',
    bonusDetails: 'বোনাসের বিবরণ',
    standardBonus: 'স্ট্যান্ডার্ড বোনাস',
    wageringRequirement: 'ওয়েজারিং প্রয়োজনীয়তা',
    beforeBalance: 'আগের ব্যালেন্স',
    completedAt: 'সম্পন্ন হয়েছে',
    noRecentTransactions: 'কোন সাম্প্রতিক লেনদেন নেই',
    depositHistoryWillAppear: 'আপনার প্রথম জমা করার পরে আপনার জমার ইতিহাস এখানে প্রদর্শিত হবে।',
    makeFirstDeposit: 'আপনার প্রথম জমা করুন',

    // ── Footer ───────────────────────────────────────────────────
    footerGaming: 'গেমিং',
    footerCasino: 'ক্যাসিনো',
    footerSlots: 'স্লটস',
    footerTable: 'টেবিল',
    footerFishing: 'ফিশিং',
    footerCrash: 'ক্র্যাশ',
    footerArcade: 'আর্কেড',
    footerLottery: 'লটারি',
    footerAbout: 'BDBa  সম্পর্কে',
    footerAboutUs: 'আমাদের সম্পর্কে',
    footerPrivacyPolicy: 'গোপনীয়তা নীতি',
    footerTerms: 'শর্তাবলী',
    footerResponsibleGaming: 'দায়িত্বশীল গেমিং',
    footerKyc: 'কেওয়াইসি',
    footerFeatures: 'বৈশিষ্ট্য',
    footerPromotions: 'প্রমোশন',
    footerVipClub: 'ভিআইপি ক্লাব',
    footerReferral: 'রেফারেল',
    footerBrandAmbassadors: 'ব্র্যান্ড অ্যাম্বাসেডর',
    footerAppDownload: 'অ্যাপ ডাউনলোড',
    footerHelp: 'সাহায্য',
    footerBjForum: 'বিজে ফোরাম',
    footerSponsorships: 'স্পনসরশিপ',
    footerOfficialPartner: 'অফিসিয়াল পার্টনার',
    footerMainSponsor: 'প্রধান স্পনসর',
    footerPrincipleSponsor: 'প্রিন্সিপাল স্পনসর',
    footerBackJersey: 'জার্সির পিছনের স্পনসর',
    footerOfficialClubSponsor: 'অফিসিয়াল ক্লাব স্পনসর',
    footerGamingLicense: 'গেমিং লাইসেন্স',
    footerOfficialBrandPartner: 'অফিসিয়াল ব্র্যান্ড পার্টনার',
    footerResponsibleGamingLabel: 'দায়িত্বশীল গেমিং',
    footerFollowUs: 'আমাদের অনুসরণ করুন',
    footerTagline: 'রাজার মতো জিতুন',
    footerShowMore: 'আরও দেখুন',
    footerShowLess: 'কম দেখুন',
    footerHeadingTitle: 'BDBabu  - বিশ্বের শীর্ষস্থানীয় অনলাইন গেমিং ও বেটিং প্ল্যাটফর্ম',
    footerHeadingText:
      'সাম্প্রতিক বছরগুলোতে বাংলাদেশে অনলাইন গেমিং ও বেটিং শিল্প ব্যাপকভাবে বিকাশ লাভ করেছে। আমাদের প্ল্যাটফর্ম বিশ্বের শীর্ষ প্রদানকারীদের কাছ থেকে বিস্তৃত গেম ও বেটিং সুযোগ প্রদান করে।',
    footerHeadingTextMore:
      'অনলাইন বেটিং মূলধারার বিনোদনে পরিণত হওয়ার সাথে সাথে, খেলোয়াড়রা বিশ্বাসযোগ্য ও বৈচিত্র্যময় প্ল্যাটফর্ম খুঁজছেন। BDBabu  শ্রেষ্ঠত্ব, নিরাপত্তা এবং অতুলনীয় গেমিং অভিজ্ঞতার জন্য খ্যাতি অর্জন করেছে।',
    footerCopyright: '© ২০২৬ BDBabu  কপিরাইট। সর্বস্বত্ব সংরক্ষিত',
    footerLegalText:
      'BDBabu  BDBabu Holdings Limited-এর মালিকানাধীন ও পরিচালিত, নিবন্ধন নম্বর ১৫৮৩৯, নিবন্ধিত ঠিকানা: হামশাহাকা, মুতাসাম্মুদু, কমোরোস ইউনিয়নের আনজোয়ান স্বায়ত্তশাসিত দ্বীপ। আমাদের সাথে যোগাযোগ করুন - BDBabu  কমোরোস ইউনিয়নের আনজোয়ান স্বায়ত্তশাসিত দ্বীপের সরকার কর্তৃক লাইসেন্সপ্রাপ্ত ও নিয়ন্ত্রিত এবং লাইসেন্স নং ALSB-202410030-FJL-এর অধীনে পরিচালিত হয়। BDBabu  সমস্ত নিয়ন্ত্রক সম্মতি পাস করেছে।',
  },

  en: {
    // ── Navigation ──────────────────────────────────────────────
    home: 'Home',
    slots: 'Slots',
    casino: 'Casino',
    profile: 'Profile',

    // ── Auth Buttons ─────────────────────────────────────────────
    login: 'Log in',
    signup: 'Sign up',
    logout: 'Log out',

    // ── Balance / Wallet ─────────────────────────────────────────
    deposit: 'Deposit',
    withdrawal: 'Withdrawal',
    refreshBalance: 'Refresh balance',

    // ── Sidebar ──────────────────────────────────────────────────
    liveChat: '24/7 Live Chat',
    language: 'Language',
    downloadApp: 'Download App',
    downloadAppNow: 'Download App Now',
    loading: 'Loading...',
    loadingCategories: 'Loading categories...',
    loadingContactOptions: 'Loading contact options...',
    viewAll: 'View all',
    promotions: 'Promotions',

    // ── Bottom Menu Items ─────────────────────────────────────────
    vipClub: 'VIP Club',
    referralProgram: 'Referral program',
    affiliate: 'Affiliate',
    brandAmbassadors: 'Brand Ambassadors',
    appDownload: 'APP Download',
    contactUs: 'Contact Us',
    newMemberGuide: 'New Member Guide',
    bjForum: 'BJ Forum',

    // ── Profile Dropdown ──────────────────────────────────────────
    username: 'Username',
    playerId: 'Player ID',
    notifications: 'Notifications',
    personalInfo: 'Personal info',
    loginSecurity: 'Login & Security',
    verification: 'Verification',
    transactions: 'Transaction records',
    bettingRecords: 'Betting records',
    turnover: 'Turnover',
    myReferral: 'My referral',

    // ── Mobile App Banner ─────────────────────────────────────────
    downloadOurApp: 'Download Our App',
    betterExperience: 'Better experience & exclusive bonuses',
    download: 'Download',

    // ── Mobile Bottom Bar ─────────────────────────────────────────
    menu: 'Menu',
    app: 'App',

    // ── Signup Success Popup ──────────────────────────────────────
    signupSuccess: 'Sign up successfully',
    signupSuccessMessage:
      'Your registration is complete and get ready for the thrill of the game! The world of sports betting is now at your fingertips. Best of luck on your bets!',
    depositNow: 'Deposit now',

    // ── Contact Platforms ─────────────────────────────────────────
    whatsapp: 'WhatsApp',
    email: 'Email',
    facebook: 'Facebook',
    instagram: 'Instagram',
    telegram: 'Telegram',
    twitter: 'Twitter',

    // ── APK Toast ────────────────────────────────────────────────
    apkDownloadStarted: 'APK Download Started!',
    failedRefreshBalance: 'Failed to refresh balance',

    // ── Register / Login Page ─────────────────────────────────────
    tabLogin: 'Log in',
    tabSignup: 'Sign up',
    phoneNumber: 'Phone number',
    enterPhoneNumber: 'Enter phone number',
    usernameLabel: 'Username',
    enterUsername: 'Enter your username',
    passwordLabel: 'Password',
    createPassword: 'Create a password',
    confirmPasswordLabel: 'Confirm Password',
    confirmPasswordPlaceholder: 'Confirm your password',
    referralCodeLabel: 'Referral Code (Optional)',
    enterReferralCode: 'Enter referral code',
    verifyBtn: 'Verify',
    checkingBtn: 'Checking...',
    changeBtn: 'Change',
    validReferralCode: '✅ Valid referral code from',
    referralFrom: 'from',
    otpSentTo: 'Enter 6-digit OTP sent to',
    otpExpiresIn: 'Expires in:',
    otpExpired: 'OTP expired',
    backBtn: 'Back',
    resendOtp: 'Resend OTP',
    resendIn: 'Resend in',
    pleaseEnterAllDigits: 'Please enter all 6 digits',
    sendOtpBtn: 'Send OTP',
    sendingOtpBtn: 'Sending OTP...',
    verifyOtpBtn: 'Verify OTP & Create Account',
    verifyingOtpBtn: 'Verifying OTP...',
    enterYourUsername: 'Enter your username',
    enterYourPassword: 'Enter your password',
    loginBtn: 'Login',
    loggingInBtn: 'Logging in...',
    forgotPassword: 'Forgot password?',
    noAccount: "Don't have an account?",
    signUpHere: 'Sign up here',
    toastOtpSent: 'OTP sent to your phone!',
    toastOtpResent: 'OTP resent successfully!',
    toastAccountCreated: 'Account created successfully!',
    toastLoginSuccess: 'Login successful!',
    toastReferralValid: 'Referral code is valid!',
    toastAffiliateWelcome: 'Welcome! You were referred by an affiliate.',
    toastUserReferralWelcome: 'Welcome! Your referral has been recorded.',
    toastFailedSendOtp: 'Failed to send OTP. Please try again.',

    // ── Category Names ────────────────────────────────────────────
    exclusive: 'Exclusive',
    sports: 'Sports',
    crash: 'Crash',
    table: 'Table',
    fishing: 'Fishing',
    arcade: 'Arcade',
    lottery: 'Lottery',

    // ── Notification Page ─────────────────────────────────────────
    pleaseLoginToViewNotifications: 'Please login to view notifications',
    failedToFetchNotifications: 'Failed to fetch notifications',
    authenticationRequired: 'Authentication Required',
    signIn: 'Sign In',
    noNotificationsYet: 'No notifications yet',
    weWillNotifyYou: "We'll notify you when something important happens.",
    showing: 'Showing',
    of: 'of',
    previous: 'Previous',
    next: 'Next',
    todayAt: 'Today at',
    yesterdayAt: 'Yesterday at',
    invalidDate: 'Invalid date',
    notificationsPageTitle: 'Notifications',

    // ── Profile Page ──────────────────────────────────────────────
    passwordsDontMatch: "New passwords don't match!",
    passwordMinLength: 'New password must be at least 6 characters long!',
    passwordChangedSuccess: 'Password changed successfully!',
    failedToChangePassword: 'Failed to change password',
    personalInfoUpdated: 'Personal information updated successfully!',
    failedToUpdateInfo: 'Failed to update information',
    verificationEmailSent: 'Verification email sent. Please check your inbox.',
    verificationSmsSent: 'Verification SMS sent. Please check your phone.',
    verifiedSuccessfully: 'verified successfully!',
    failedToVerify: 'Failed to verify',
    failedToUpdate2FA: 'Failed to update 2FA settings',
    verified: 'Verified',
    pending: 'Pending',
    notStarted: 'Not Started',
    rejected: 'Rejected',
    copiedToClipboard: 'Copied to clipboard!',
    edit: 'Edit',
    saving: 'Saving...',
    save: 'Save',
    cancel: 'Cancel',
    notSet: 'Not set',
    fullLegalName: 'Full legal name',
    enterFullName: 'Enter your full name',
    dateOfBirth: 'Date of birth',
    phone: 'Phone',
    enterPhoneNumber: 'Enter your phone number',
    email: 'Email',
    manage: 'Manage',
    changePassword: 'Change Password',
    currentPassword: 'Current Password',
    newPassword: 'New Password',
    confirmNewPassword: 'Confirm New Password',
    securitySettings: 'Security Settings',
    twoFactorAuth: 'Two-Factor Authentication',
    extraSecurityLayer: 'Add an extra layer of security',
    enable: 'Enable',
    disable: 'Disable',
    loginAlerts: 'Login Alerts',
    notifyNewLogins: 'Get notified of new logins',
    enabled: 'Enabled',
    activeSessions: 'Active Sessions',
    manageActiveLogins: 'Manage your active logins',
    viewAll: 'View All',
    verificationDescription: 'Complete your verification to access all features and increase your limits.',
    emailVerification: 'Email Verification',
    emailVerificationDesc: 'Verify your email address to receive important notifications and updates.',
    verifyEmail: 'Verify Email',
    phoneVerification: 'Phone Verification',
    phoneVerificationDesc: 'Verify your phone number for additional security and faster withdrawals.',
    verifyPhone: 'Verify Phone',
    identityVerification: 'Identity Verification',
    identityVerificationDesc: 'Upload a government-issued ID to verify your identity.',
    startVerification: 'Start Verification',
    addressVerification: 'Address Verification',
    addressVerificationDesc: 'Verify your address with a recent utility bill or bank statement.',
    verifyAddress: 'Verify Address',
    resendCode: 'Resend Code',
    enterVerificationCode: 'Enter verification code for',

    // ── Transaction Page ──────────────────────────────────────────
    transactionRecords: 'Transaction records',
    filters: 'Filters',
    type: 'Type',
    status: 'Status',
    startDate: 'Start Date',
    endDate: 'End Date',
    allTypes: 'All Types',
    allStatus: 'All Status',
    clearFilters: 'Clear Filters',
    applyFilters: 'Apply Filters',
    failedToFetchTransactions: 'Failed to fetch transactions',
    failedToLoadTransactions: 'Failed to load transactions. Please try again.',
    noTransactionsFound: 'No transactions found',
    tryAgain: 'Try Again',
    completed: 'Completed',
    failed: 'Failed',
    cancelled: 'Cancelled',
    bank: 'Bank',
    crypto: 'Crypto',
    currencySymbol: '৳',
    dateFormat: 'MMM dd, yyyy HH:mm',

    // ── Betting Records Page ──────────────────────────────────────
    bettingRecords: 'Betting Records',
    settled: 'Settled',
    unsettled: 'Unsettled',
    last7Days: 'Last 7 days',
    transaction: 'Transaction',
    game: 'Game',
    betAmount: 'Bet Amount',
    winAmount: 'Win Amount',
    netAmount: 'Net Amount',
    dateTime: 'Date & Time',
    platform: 'Platform',
    gameType: 'Game Type',
    won: 'Won',
    lost: 'Lost',
    failedToFetchBettingRecords: 'Failed to fetch betting records',
    loadingBettingRecords: 'Loading betting records...',
    retry: 'Retry',
    noSettledRecords: 'No settled betting records found',
    noUnsettledRecords: 'No unsettled betting records found',
    cricket: 'Cricket',
    football: 'Football',
    tennis: 'Tennis',
    basketball: 'Basketball',
bonuses: 'bonuses',
noBonusesAvailable: 'No Bonuses Available',
noBonusesMessage: "You don't have any bonuses available at the moment. Check back later for new offers and rewards!",
vipClub: 'VIP Club',
    // ── Turnover Page ─────────────────────────────────────────────
    turnoverRequirement: 'Turnover Requirement',
    turnoverDescription: 'Complete wagering requirements to enable withdrawals',
    refresh: 'Refresh',
    loadingTurnoverData: 'Loading turnover data',
    failedToFetchUserData: 'Failed to fetch user data',
    pleaseLoginToViewProfile: 'Please login to view your profile',
    noTurnoverRequirement: 'No Turnover Requirement',
    noTurnoverRequirementDesc: "You don't have any wagering requirements at the moment.",
    freeWithdrawalMessage: 'You can withdraw freely as there are no turnover restrictions.',
    wageringRequirement: 'Wagering Requirement',
    betDepositMultiplier: 'Bet {multiplier}x your deposit amount',
    inProgress: 'In Progress',
    progress: 'Progress',
    depositAmount: 'Deposit Amount',
    bonuses: 'bonuses',
    requiredTurnover: 'Required Turnover',
    completedWagering: 'Completed Wagering',
    remaining: 'Remaining',
    wageringCompleted: 'Wagering Requirement Completed!',
    wageringCompletedDesc: 'You have successfully completed the wagering requirement. You can now make withdrawals.',
    wageringPending: 'Wagering Requirement Pending',
    wageringPendingDesc: 'You need to bet {currency}{amount} more to complete the requirement.',
    currentProgress: 'Current Progress',
    howTurnoverWorks: 'How Turnover Works',
    depositTurnover: 'Deposit Turnover',
    depositTurnoverDesc: 'You need to bet {multiplier} times your deposit amount ({currency}{amount}) before making withdrawals.',
    wageringProgress: 'Wagering Progress',
    wageringProgressDesc: 'Your current betting amount is {currency}{completed} out of required {currency}{required}.',
    importantNotes: 'Important Notes',
    importantNote1: 'You must complete wagering requirements before making withdrawals',
    importantNote2: 'Only settled bets count towards wagering requirements',
    importantNote3: 'Required turnover: {multiplier} × {currency}{deposit} = {currency}{required}',
    importantNote4: 'Withdrawals are restricted until wagering is completed',
    currentBalance: 'Current Balance',
    totalDeposit: 'Total Deposit',
    totalBet: 'Total Bet',
    turnoverStatus: 'Turnover Status',
    complete: 'Complete',

    // ── My Referral Page ──────────────────────────────────────────
    info: 'Info',
    details: 'Details',
    yourReferralCode: 'Your referral code',
    copyReferralCode: 'Copy referral code',
    shareCodeMessage: 'Share this code with friends to earn rewards',
    copyLink: 'Copy Link',
    share: 'Share',
    activeDownlines: 'Active downlines',
    lifetimeRewards: 'Lifetime rewards',
    referralTurnover: 'Referral turnover',
    cashRewards: 'Cash rewards',
    referredUsers: 'Referred Users',
    userId: 'User ID',
    joinedDate: 'Joined Date',
    earnedAmount: 'Earned Amount',
    noReferralsYet: 'No referrals yet',
    shareReferralMessage: 'Share your referral code to start earning rewards',
    howReferralWorks: 'How Our Referral Program Works',
    shareYourCode: 'Share Your Code',
    shareCodeDesc: "Share your unique referral code with friends. They'll use it when signing up for your app.",
    earnRewards: 'Earn Rewards',
    earnRewardsDesc: "When your friend makes their first deposit or completes qualifying activities, you'll earn rewards.",
    trackEarnings: 'Track Your Earnings',
    trackEarningsDesc: "Monitor your referral earnings and statistics in real-time on this dashboard.",
    termsConditions: 'Terms & Conditions',
    term1: 'Referral rewards are subject to terms and conditions',
    term2: 'Abuse of the referral system may result in account suspension',
    term3: 'Rewards may take up to 24 hours to appear in your account',
    term4: 'Minimum withdrawal limits may apply to referral earnings',
    joinMe: 'Join me!',
    useMyReferralCode: 'Use my referral code to sign up',
    error: 'Error',
    copied: 'Copied!',
    internalServerError: 'Internal server error',
    // Add to en object (after existing entries)
    exclusiveBonuses: 'Exclusive Bonuses & Rewards',
    claimCashBonusesDesc: 'Claim instant cash bonuses, special offers, and loyalty rewards directly to your wallet balance',
    availableBonuses: 'Available Bonuses',
    claimCashBonuses: 'Claim cash bonuses directly added to your account balance',
    failedToFetchBonuses: 'Failed to fetch bonuses',
    pleaseLoginToViewBonuses: 'Please login to view bonuses',
    checkBackLater: 'Check back later for special offers and bonuses.',
    bonusDetails: 'Bonus Details',
    validity: 'Validity',
    created: 'Created',
    expires: 'Expires',
    never: 'Never',
    neverExpires: 'Never expires',
    expired: 'Expired',
    expiresToday: 'Expires today',
    daysLeft: 'days left',
    claimNow: 'Claim Now',
    claimBonus: 'Claim Bonus',
    confirmClaimMessage: 'Are you sure you want to claim this bonus?',
    confirmClaim: 'Confirm Claim',
    bonus: 'Bonus',
    amount: 'Amount',
    type: 'Type',
    occasion: 'Occasion',
    invalidDate: 'Invalid date',
    noExpiry: 'No expiry',
    todayAt: 'Today at',
    // Add these to the en object (English)
    depositFunds: 'Deposit Funds',
    depositDescription: 'Add money to your account using OraclePay secure payment gateway',
    failedToFetchDepositMethods: 'Failed to load deposit methods',
    failedToFetchUserData: 'Failed to fetch user data',
    loadingDepositMethods: 'Loading Deposit methods...',
    noDepositMethodsAvailable: 'No deposit methods available at the moment.',
    amountCurrency: 'Amount (৳)',
    enterDepositAmount: 'Enter deposit amount',
    selectBonusOptional: 'Select Bonus (Optional)',
    loadingBonuses: 'Loading bonuses...',
    noBonus: 'No Bonus',
    proceedWithoutBonus: 'Proceed without bonus',
    bonusCode: 'Code',
    noBonusesAvailable: 'No bonuses available at the moment.',
    transactionSummary: 'Transaction Summary',
    depositAmount: 'Deposit Amount',
    bonus: 'Bonus',
    totalCredit: 'Total Credit',
    proceedTo: 'Proceed to',
    payment: 'Payment',
    processing: 'Processing...',
    selectPaymentMethod: 'Please select a payment method',
    amountRequired: 'Amount is required',
    minDepositAmount: 'Minimum deposit amount is ৳5',
    amountMustBeWholeNumber: 'Amount must be a whole number',
    maxDepositAmount: 'Maximum deposit amount is',
    pleaseSelectPaymentMethod: 'Please select a payment method',
    redirectingToPaymentPage: 'Redirecting to payment page...',
    failedToGeneratePayment: 'Failed to generate payment',
    paymentGenerationFailed: 'Payment generation failed. Please try again.',
    invalidPaymentRequest: 'Invalid payment request. Please check your input.',
    invalidApiToken: 'Invalid API token. Please contact support.',
    accessDenied: 'Access denied. Please contact support.',
    authenticationTokenNotFound: 'Authentication token not found',
    balanceUpdatedSuccessfully: 'Balance updated successfully!',
    failedToRefreshBalance: 'Failed to refresh balance',
    justNow: 'just now',
    minutesAgo: 'minutes ago',
    hoursAgo: 'hours ago',
    daysAgo: 'days ago',
    error: 'Error',
    tryAgain: 'Try Again',
    currentBalance: 'Current Balance',
    bonusBalance: 'Bonus Balance',
    refreshBalance: 'Refresh Balance',
    accountInformation: 'Account Information',
    playerId: 'Player ID',
    username: 'Username',
    phone: 'Phone',
    howToDepositWithOraclePay: 'How to deposit with Opay',
    selectPaymentMethod: 'Select your preferred payment method',
    enterDepositAmountInstruction: 'Enter the amount you want to deposit',
    selectBonusIfAvailable: 'Select a bonus option if available (optional)',
    clickProceedToPayment: 'Click "Proceed to [Payment Method] Payment"',
    redirectedToOraclePay: 'You will be redirected to Opay secure payment page',
    completePayment: 'Complete the payment using your chosen method',
    redirectedBack: "After successful payment, you'll be redirected back",
    balanceUpdated: 'Your balance will be updated automatically',
    recentTransactions: 'Recent Transactions',
    viewAll: 'View All',
    transactionId: 'ID',
    session: 'Session',
    refreshCoinBalance: "Refresh Coin Balance",
    coinBalanceRefreshed: "Coin balance refreshed!",
    failedRefreshCoinBalance: "Failed to refresh coin balance",
    bonusDetails: 'Bonus Details',
    standardBonus: 'Standard Bonus',
    wageringRequirement: 'Wagering Requirement',
    beforeBalance: 'Before Balance',
    completedAt: 'Completed',
    noRecentTransactions: 'No Recent Transactions',
    depositHistoryWillAppear: 'Your deposit history will appear here once you make your first deposit.',
    makeFirstDeposit: 'Make Your First Deposit',
    // ── Footer ───────────────────────────────────────────────────
    footerGaming: 'Gaming',
    footerCasino: 'Casino',
    footerSlots: 'Slots',
    footerTable: 'Table',
    footerFishing: 'Fishing',
    footerCrash: 'Crash',
    footerArcade: 'Arcade',
    footerLottery: 'Lottery',
    footerAbout: 'About BDBabu',
    footerAboutUs: 'About Us',
    footerPrivacyPolicy: 'Privacy Policy',
    footerTerms: 'Terms & Conditions',
    footerResponsibleGaming: 'Responsible Gaming',
    footerKyc: 'KYC',
    footerFeatures: 'Features',
    footerPromotions: 'Promotions',
    footerVipClub: 'VIP Club',
    footerReferral: 'Referral',
    footerBrandAmbassadors: 'Brand Ambassadors',
    footerAppDownload: 'APP Download',
    footerHelp: 'Help',
    footerBjForum: 'BJ Forum',
    footerSponsorships: 'Sponsorships',
    footerOfficialPartner: 'Official Partner',
    footerMainSponsor: 'Main Sponsor',
    footerPrincipleSponsor: 'Principle Sponsor',
    footerBackJersey: 'Back of Jersey Sponsor',
    footerOfficialClubSponsor: 'Official Club Sponsor',
    footerGamingLicense: 'Gaming License',
    footerOfficialBrandPartner: 'Official Brand Partner',
    footerResponsibleGamingLabel: 'Responsible Gaming',
    footerFollowUs: 'Follow Us',
    footerTagline: 'Win Like A King',
    footerShowMore: 'Show more',
    footerShowLess: 'Show less',
    footerHeadingTitle:
      'BDBabu - Leading Online Gaming and Betting Platform',
    footerHeadingText:
      'In recent years, the online gaming and betting industry has seen exponential growth, attracting players who seek excitement and rewarding experiences. Our platform stands out as a top choice, offering an extensive range of games and betting opportunities from renowned providers worldwide.',
    footerHeadingTextMore:
      'With online betting becoming a mainstream entertainment choice, players are looking for a platform that offer both trust and variety. Among the most established names in the industry, BDBabu has built a reputation for excellence, security, and an unparalleled gaming experience.',
    footerCopyright: '© 2026 BDBabu Copyrights. All rights Reserved',
    footerLegalText:
      'BDBabu owned and operated by BDBabu Holdings Limited, registration number 15839, registered address: Hamshahaka, Mutasammudu, Autonomous Island of Anjouan, Union of Comoros. Contact us is licensed and regulated by the Government of the Autonomous Island of Anjouan, Union of Comoros and operates under License No. ALSB-202410030-FJL. BDBabu has passed all regulatory compliance and is legally authorized to conduct gaming operations for any and all games of chance and wagering.',
  },
};

export const LanguageProvider = ({ children }) => {
  const [language, setLanguage] = useState(() => {
    const savedLanguage = localStorage.getItem('language');
    return savedLanguage
      ? JSON.parse(savedLanguage)
      : {
        code: 'bn',
        name: 'বাংলা',
        flag: 'https://images.5849492029.com//TCG_PROD_IMAGES/COUNTRY_FLAG/CIRCLE/BD.svg',
      };
  });

  useEffect(() => {
    localStorage.setItem('language', JSON.stringify(language));
  }, [language]);

  const changeLanguage = (lang) => {
    setLanguage(lang);
  };

  return (
    <LanguageContext.Provider
      value={{ language, changeLanguage, t: translations[language.code] }}
    >
      {children}
    </LanguageContext.Provider>
  );
};