import React, { useState, useEffect, useRef } from 'react';
import { 
  FaFacebook, FaTwitter, FaInstagram, FaLinkedin, FaEnvelope, FaPhone, 
  FaChartLine, FaUsers, FaHeadset, FaChevronDown, FaChevronUp 
} from 'react-icons/fa';
import { NavLink, useNavigate } from "react-router-dom";
import axios from 'axios';
import Typed from 'typed.js';
import logo from "../assets/logo.png";
import affiliate_img from "../assets/affiliate.png";

const Home = () => {
  const [openFaq, setOpenFaq] = useState(null);
  const [dynamicLogo, setDynamicLogo] = useState(logo);
  const navigate = useNavigate();
  const el = useRef(null);
  const base_url = import.meta.env.VITE_API_KEY_Base_URL;

  // Typing Effect Logic
  useEffect(() => {
    const typed = new Typed(el.current, {
      strings: ['60% COMMISSION', 'LIFETIME REVENUE'],
      typeSpeed: 100,
      backSpeed: 50,
      backDelay: 2000,
      loop: true,
      showCursor: true,
      cursorChar: '|',
    });

    return () => {
      typed.destroy();
    };
  }, []);

  const fetchBrandingData = async () => {
    try {
      const response = await axios.get(`${base_url}/api/branding`);
      if (response.data.success && response.data.data?.logo) {
        const logoUrl = response.data.data.logo.startsWith('http') 
          ? response.data.data.logo 
          : `${base_url}${response.data.data.logo.startsWith('/') ? '' : '/'}${response.data.data.logo}`;
        setDynamicLogo(logoUrl);
      }
    } catch (error) {
      console.error("Branding error:", error);
    }
  };

  useEffect(() => {
    fetchBrandingData();
  }, []);

  const faqData = [
    {
      question: "How do I join the BDBabu Affiliate Program?",
      answer: "Simply click 'Join Now', fill out the registration form with your details and preferred payment method. Our team reviews applications within 24-48 hours."
    },
    {
      question: "How is the 60% commission calculated?",
      answer: "Elite partners with high-volume referrals qualify for our top-tier 60% revenue share. This is based on the net profit generated by your referred players."
    },
    {
      question: "When and how do I get paid?",
      answer: "Payments are processed monthly. We support bKash, Nagad, Rocket, and Binance (USDT) for fast and secure withdrawals."
    },
    {
      question: "Do I get marketing support?",
      answer: "Yes! We provide high-converting banners, landing pages, and a dedicated affiliate manager to help you optimize your campaigns."
    }
  ];

  return (
    <div className="min-h-screen bg-[#000514] text-white font-sans selection:bg-cyan-500 selection:text-black">
      {/* --- BACKGROUND DECORATION --- */}
      <div className="fixed inset-0 pointer-events-none z-0">
        <div className="absolute top-[-10%] left-[-10%] w-[40%] h-[40%] bg-cyan-500/10 rounded-full blur-[120px]"></div>
        <div className="absolute bottom-[-10%] right-[-10%] w-[40%] h-[40%] bg-blue-600/10 rounded-full blur-[120px]"></div>
      </div>

      <style>{`
        ::-webkit-scrollbar { width: 8px; }
        ::-webkit-scrollbar-track { background: #000514; }
        ::-webkit-scrollbar-thumb {
          background: linear-gradient(180deg, #22d3ee 0%, #2563eb 100%);
          border-radius: 20px;
        }
        ::-webkit-scrollbar-thumb:hover { background: #22d3ee; }
      `}</style>

      {/* --- HEADER --- */}
      <header className="sticky top-0 z-50 backdrop-blur-md border-b border-white/10">
        <div className="container mx-auto px-4 md:px-6 py-3 md:py-4 flex justify-between items-center">
          <img src={dynamicLogo} alt="LOGO" className="h-7 md:h-14 object-contain" />
          
          {/* Navigation - Always visible buttons, hidden links on mobile */}
          <div className="flex items-center gap-2 md:gap-8">
            <nav className="hidden md:flex items-center space-x-8 mr-4">
              {['Home', 'About', 'Commission', 'FAQ'].map((item) => (
                <a key={item} href={`#${item.toLowerCase()}`} className="text-xs font-black uppercase tracking-widest text-gray-400 hover:text-cyan-400 transition-colors">
                  {item}
                </a>
              ))}
            </nav>
            
            {/* Buttons Group - Direct access on mobile */}
            <div className="flex items-center gap-2">
              <NavLink to="/login" className="text-[10px] md:text-xs font-black uppercase border border-cyan-500/50 px-3 py-2 md:px-6 md:py-2 rounded-tl-md rounded-br-md hover:bg-cyan-500/10 transition-all whitespace-nowrap">
                Login
              </NavLink>
              <NavLink to="/register" className="text-[10px] md:text-xs font-black uppercase bg-gradient-to-r from-cyan-400 to-blue-600 px-3 py-2 md:px-6 md:py-2 rounded-tl-md rounded-br-md text-black hover:brightness-110 transition-all shadow-[0_0_15px_rgba(34,211,238,0.3)] whitespace-nowrap">
                Sign Up
              </NavLink>
            </div>
          </div>
        </div>
      </header>

      {/* --- HERO SECTION --- */}
      <section id="home" className="relative pt-12 md:pt-20 pb-20 md:pb-32 px-6 overflow-hidden">
        <div className="container mx-auto grid lg:grid-cols-2 gap-12 items-center">
          <div className="z-10 text-center lg:text-left">
            <h1 className="text-3xl md:text-6xl font-bold uppercase tracking-tighter leading-none mb-6">
              EARN UP TO <br />
              <span className="text-transparent bg-clip-text bg-gradient-to-r from-cyan-400 to-blue-500" ref={el}></span>
            </h1>
            <p className="text-gray-400 text-sm md:text-xl mb-10 max-w-xl mx-auto lg:mx-0">
              Join Asia's most powerful affiliate network. Transform your traffic into a sustainable revenue stream with BDBabu.
            </p>
            <button
              onClick={() => navigate("/register")} 
              className="group relative px-8 py-4 md:px-12 cursor-pointer md:py-5 bg-cyan-500 text-black text-xs md:text-sm font-black uppercase tracking-[0.2em] rounded-sm transition-all duration-300 hover:scale-105 hover:bg-white active:scale-95 hover:shadow-[0_0_40px_rgba(6,182,212,0.6)]"
            >
              <span className="relative z-10 flex items-center gap-2">Start Earning Now</span>
              <div className="absolute -top-1 -right-1 w-3 h-3 border-t-2 border-r-2 border-cyan-400 group-hover:border-white"></div>
              <div className="absolute -bottom-1 -left-1 w-3 h-3 border-b-2 border-l-2 border-cyan-400 group-hover:border-white"></div>
            </button>
          </div>
          <div className="relative flex justify-center">
             <div className="absolute inset-0 bg-cyan-500/20 blur-[100px] rounded-full"></div>
             <img src={affiliate_img} alt="Dashboard" className="relative z-10 w-[90%] md:w-[80%] animate-pulse-slow" />
          </div>
        </div>
      </section>

      {/* --- ABOUT SECTION --- */}
      <section id="about" className="py-20 bg-[#01081a]">
        <div className="container mx-auto px-6">
          <div className="max-w-4xl mx-auto text-center mb-16">
            <h2 className="text-2xl md:text-5xl font-black uppercase mb-6">Who We Are</h2>
            <div className="h-1.5 w-24 bg-cyan-500 mx-auto mb-8"></div>
            <p className="text-gray-400 text-sm md:text-lg leading-relaxed">
              BDBabu Affiliate is a global leader in performance marketing. We provide a transparent, high-tech platform designed for influencers and marketers to monetize effectively.
            </p>
          </div>
          <div className="grid md:grid-cols-3 gap-8">
            {[
              { icon: <FaChartLine />, title: "Real-time Analytics", desc: "Track every click and conversion with our sub-second latency dashboard." },
              { icon: <FaUsers />, title: "High Retention", desc: "Our premium services keep your players active longer, increasing your LTV." },
              { icon: <FaHeadset />, title: "24/7 Support", desc: "Dedicated account managers to help you scale your campaigns." }
            ].map((feature, i) => (
              <div key={i} className="p-8 bg-white/5 border border-white/10 rounded-xl hover:border-cyan-500/50 transition-all group text-center md:text-left">
                <div className="text-3xl md:text-4xl text-cyan-400 mb-6 flex justify-center md:justify-start group-hover:scale-110 transition-transform">{feature.icon}</div>
                <h3 className="text-lg md:text-xl font-bold uppercase mb-4">{feature.title}</h3>
                <p className="text-gray-500 text-xs md:text-sm leading-relaxed">{feature.desc}</p>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* --- COMMISSION SECTION --- */}
      <section id="commission" className="py-20 px-6">
        <div className="container mx-auto">
          <div className="text-center mb-16">
            <h2 className="text-2xl md:text-5xl font-black uppercase mb-4">Commission Structure</h2>
            <p className="text-cyan-400 text-[10px] md:text-sm font-bold tracking-[0.2em] md:tracking-[0.3em] uppercase">The More You Refer, The More You Earn</p>
          </div>
          <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-6">
            {[
              { tier: "Bronze", comm: "25%", users: "1-10", color: "from-orange-700 to-orange-500" },
              { tier: "Silver", comm: "35%", users: "11-30", color: "from-gray-400 to-gray-200" },
              { tier: "Gold", comm: "45%", users: "31-100", color: "from-yellow-600 to-yellow-400" },
              { tier: "Elite", comm: "60%", users: "100+", color: "from-cyan-500 to-blue-600" }
            ].map((p, i) => (
              <div key={i} className={`p-8 rounded-2xl bg-gradient-to-br ${p.color} text-black transform hover:-translate-y-2 transition-all shadow-xl text-center md:text-left`}>
                <h4 className="font-black uppercase tracking-widest mb-2 text-xs md:text-sm">{p.tier}</h4>
                <div className="text-4xl md:text-5xl font-black mb-4">{p.comm}</div>
                <div className="mt-6 pt-6 border-t border-black/10 text-[10px] font-black uppercase">Lifetime Revenue Share</div>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* --- FAQ SECTION --- */}
      <section id="faq" className="py-20 px-6">
        <div className="container mx-auto max-w-3xl">
          <h2 className="text-2xl md:text-5xl font-black uppercase mb-12 text-center">Frequently Asked</h2>
          <div className="space-y-4">
            {faqData.map((faq, idx) => (
              <div key={idx} className="border border-white/10 rounded-lg overflow-hidden bg-white/5">
                <button 
                  onClick={() => setOpenFaq(openFaq === idx ? null : idx)}
                  className="w-full px-4 py-4 md:px-6 md:py-5 text-left flex justify-between items-center hover:bg-white/5 transition-colors"
                >
                  <span className="font-bold uppercase text-[10px] md:text-sm tracking-widest">{faq.question}</span>
                  {openFaq === idx ? <FaChevronUp className="text-cyan-400" /> : <FaChevronDown />}
                </button>
                {openFaq === idx && (
                  <div className="px-6 py-5 text-gray-400 text-xs md:text-sm border-t border-white/10 leading-relaxed bg-[#000514]/50">
                    {faq.answer}
                  </div>
                )}
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* --- FOOTER --- */}
      <footer id="contact" className="py-20 border-t border-white/10 bg-[#000514]">
        <div className="container mx-auto px-6 grid md:grid-cols-4 gap-12">
          <div className="md:col-span-2">
            <img src={dynamicLogo} alt="LOGO" className="h-10 mb-6 mx-auto md:mx-0" />
            <p className="text-gray-500 max-w-sm mb-6 uppercase text-[9px] md:text-[10px] font-bold tracking-[0.2em] leading-loose text-center md:text-left">
              The world's most rewarding affiliate network. Join the BojiMan of earners today.
            </p>
            <div className="flex justify-center md:justify-start space-x-4">
              {[FaFacebook, FaTwitter, FaInstagram, FaLinkedin].map((Icon, i) => (
                <a key={i} href="#" className="w-10 h-10 rounded-full border border-white/10 flex items-center justify-center text-gray-400 hover:border-cyan-400 hover:text-cyan-400 transition-all">
                  <Icon />
                </a>
              ))}
            </div>
          </div>
          <div className="text-center md:text-left">
            <h4 className="text-[10px] font-black uppercase tracking-[0.3em] mb-6 text-cyan-400">Navigation</h4>
            <ul className="space-y-4 text-[10px] font-bold uppercase text-gray-500 tracking-widest">
              <li><a href="#home" className="hover:text-white">Home</a></li>
              <li><a href="#about" className="hover:text-white">About Us</a></li>
              <li><a href="#commission" className="hover:text-white">Commission</a></li>
              <li><a href="#faq" className="hover:text-white">FAQ</a></li>
            </ul>
          </div>
          <div className="text-center md:text-left">
            <h4 className="text-[10px] font-black uppercase tracking-[0.3em] mb-6 text-cyan-400">Support</h4>
            <ul className="space-y-4 text-[10px] font-bold uppercase text-gray-500 tracking-widest">
              <li className="flex items-center justify-center md:justify-start space-x-2"><FaEnvelope className="text-cyan-400" /> <span>affiliate@bdbabu.com</span></li>
              <li className="flex items-center justify-center md:justify-start space-x-2"><FaPhone className="text-cyan-400" /> <span>+44 731 1133 789</span></li>
            </ul>
          </div>
        </div>
        <div className="container mx-auto px-6 mt-20 pt-8 border-t border-white/5 text-center">
          <p className="text-[8px] md:text-[10px] font-black text-gray-700 tracking-[0.5em] uppercase">
            © {new Date().getFullYear()} BDBabu Affiliate Network. All Rights Reserved.
          </p>
        </div>
      </footer>
    </div>
  );
};

export default Home;